server:
  port: 8083
  
spring:
  application:
    name: cassandrajtv-server
  security:
    user:
      name: root
      password: root
  data:
    cassandra:
      keyspace-name: cjavadatabase
      contact-points: localhost
      port: 9042
      schema-action: create-if-not-exists
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
            #defaultZone: http://localhost:8761/eureka/
            defaultZone: http://root:root@localhost:8761/eureka
#            defaultZone: http://user:password@localhost:8761/eureka
  instance:
    hostname: localhost